baseURL = "https://festive-leakey-8479ba.netlify.com/"
languageCode = "en-us"
title = "Zkynet.io"
theme = "ghostwriter"

[Params]
    description = "My description"
    github = "https://github.com/XXX"
    instagramUrl = "https://instagram.com"
    githubUrl = "https://github.com"
    youtubeUrl = "https://youtube.com"
    twitterUrl = "https://twitter.com"
    blogUrl = "/blog"
    instagramLogo = "../../icons/instagram-off.png"
    githubLogo = "../../icons/github-off.png"
    youtubeLogo = "../../icons/youtube-off.png"
    twitterLogo = "../../icons/twitter-off.png"
    blogLogo = "../../icons/blog-off.png"
    twitter = "https://twitter.com/XXX"
    youtube = "https://youtube.com"
    email = "anon@zkynet.io"
    dateFormat = "Mon, Jan 2, 2006"
    zkynetLogo = "../../img/zkynet-logo.png"
    contactImg = "../../img/zkynet-contact.png"
    zenbot = "../../img/zenbot.png"
    plugImg = "../../icons/plug.png"

[Permalinks]
    post = "/:year/:month/:day/:filename/"
