baseURL = "https://www.zkynet.io/"
languageCode = "en-us"
title = "Zkynet.io"
theme = "ghostwriter"

[Params]
    description = "My description"
    youtubeUrl = "https://youtube.com"
    facebookUrl = "https://facebook.com"
    twitterUrl = "https://twitter.com"
    blogUrl = "/blog"
    youtubeLogo = "../../icons/red-button.png"
    facebookLogo = "../../icons/red-button.png"
    twitterLogo = "../../icons/red-button.png"
    contactLogo = "../../icons/red-button.png"
    blogLogoActive = "../../icons/red-.png"
    blogLogoInactive = "../../icons/red-button.png"
    contactEmail = "anon@zkynet.io"
    dateFormat = "Mon, Jan 2, 2006"
    zkynetLogo = "../../img/zkynet-logo.png"
    zenbot = "../../img/zenbot.png"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    identifier = "blog"
    name = "This is the blog section"
    title = "blog section"
    url = "/blog/"
    weight = 1
    pre = "../../icons/black-button.png"
    post = "../../icons/red-button.png"
